### ISSUE TITLE
Interpolator has different behaviour to scipy RBF

### ISSUE THREAD

**Issue by AndrewHartAR** [ArmanMaesumi/torchrbf#1]
I've setup an interpolator with survey data, to interpolate signal strength of specific wifi APs. The survey data covers the indoor space.

Here is the code setting up scipy interpolator:

```
    xs = [grid_point.x for grid_point in grid_points]
    ys = [grid_point.y for grid_point in grid_points]
    rssis = [scan['RSSI'] for scan in ap_survey_scans]
    interpolator = Rbf(xs, ys, rssis, function='linear', smooth=20)
```

Here it is for torchtbf. It runs many orders of magnitude faster with torchrbf 🔥:

```
    grid_points = torch.tensor([([grid_point.x, grid_point.y]) for grid_point in grid_points])
    rssis = torch.tensor([scan['RSSI'] for scan in ap_survey_scans]).unsqueeze(1)
    interpolator = RBFInterpolator(grid_points, rssis, smoothing=20.0, kernel='linear')
```

This is the survey data provided, each black dot representing a data point:
<img width="767" alt="Screenshot 2023-08-28 at 09 02 34" src="https://github.com/ArmanMaesumi/torchrbf/assets/1865635/b3bcdd07-a3ec-4dbb-86b9-83c891b9b17b">

This is the results of interpolated signal from an individual AP. I've visualised it where larger dots == stronger interpolated signal:
<img width="1048" alt="Screenshot 2023-08-28 at 08 50 07" src="https://github.com/ArmanMaesumi/torchrbf/assets/1865635/e2f30f1b-0dac-434b-8197-ffba5b7b8656">

This is the results (visualised in red this time) from torchrbf:
<img width="1034" alt="Screenshot 2023-08-28 at 08 49 44" src="https://github.com/ArmanMaesumi/torchrbf/assets/1865635/077f02b4-e05b-4542-bd61-fa6a973c090e">

What's happening here is that outside of the survey area, torchrbf has a harder time interpolating the way the signal should decrease.

Let me know if there's more data I can provide to help resolve this issue (can provide data privately if it's helpful).

**Comment by ArmanMaesumi** [comment]
Thanks for raising this issue!

I notice you are using scipy's `Rbf`, which is deprecated. torchrbf was based on scipy's `RBFInterpolator` instead.

After a bit of testing, I found that the interpolant's behavior in `scipy.interpolate.Rbf` is significantly different than `scipy.interpolate.RBFInterpolator`. The discrepancy that I observe is specifically when using the linear kernel and querying the interpolator outside of the data's convex hull. `Rbf` values seem to nicely falloff to zero, whereas `RBFInterpolator` does not. In your code it would be interesting to see how scipy's RBFInterpolator behaves. I need to dig further to figure out where the discrepancy is coming from though.

In any case I think you should be using a different kernel -- namely `inverse_quadratic`. Since you are modeling signal strength, we'd expect the data to falloff via some inverse square function, so `inverse_quadratic` or even `gaussian` are good options. They should also behave as you'd hope in the extrapolative case (they will _definitely_ falloff to zero).

If you use these kernels you'll need to specify a shape parameter in the interpolator's constructor, e.g. `epsilon=5` (you can play with this value a bit to see what works). 

Let me know if that gives better results for the time being :)

**Comment by ArmanMaesumi** [comment]
Now I'm more convinced scipy's old `Rbf` has a bug:

If you use a linear kernel `f(r) = r`, then one would expect the interpolated signal to diverge as `r -> infinity`. This is indeed what we see with torchrbf and scipy's new interpolator. 

Here is a very basic example using the linear kernel and `smoothing = 0`. We have two points (with values 0.0, and 1.0) on opposite sides of the unit square. The result of `Rbf` (on the right side) does not make any sense. The extrapolated result shows a strange radial pattern, even though the data should (symmetrically) divide the plane into two sides.

![image](https://github.com/ArmanMaesumi/torchrbf/assets/8769053/b6bf907e-2393-41dc-9a01-da0cc7479cc3)

**Comment by AndrewHartAR** [comment]
🙌
